import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  TextInput,
  ScrollView,
  SafeAreaView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const PaymentLinkTestScreen = ({ navigation }) => {
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);
  const [activeTab, setActiveTab] = useState('paymentLink'); // 'paymentLink' or 'staticLink'

  const switchTab = (tab) => {
    setActiveTab(tab);
    // Generate new order ID when switching tabs
    updateFormData('order_id', generateDisplayOrderId());
  };
  
  // Calculate default expiry date (30 days from today)
  const getDefaultExpiryDate = () => {
    const today = new Date();
    const expiryDate = new Date(today.getTime() + (30 * 24 * 60 * 60 * 1000)); // 30 days from today
    return expiryDate.toISOString().split('T')[0]; // Format as YYYY-MM-DD
  };

  // Generate unique order ID (for display purposes only - server will generate the actual one)
  const generateDisplayOrderId = () => {
    const timestamp = Date.now().toString();
    const timestampSuffix = timestamp.substring(timestamp.length - 4);
    const random = Math.floor(Math.random() * 9999).toString().padStart(4, '0');
    const uniqueId = (timestampSuffix + random).substring(0, 4);
    return `OR-DOIT-${uniqueId}`;
  };

  // Form state
  const [formData, setFormData] = useState({
    req_user_id: 'yagou381',
    me_id: '202508080001',
    amount: '500',
    customer_email: 'test@example.com',
    mobile_no: '0965680964',
    expiry_date: getDefaultExpiryDate(),
    order_id: generateDisplayOrderId(), // Generate unique order ID for display
    first_name: 'YagoutPay',
    last_name: 'TestUser',
    product: 'Test Product',
    dial_code: '+251',
    failure_url: 'http://localhost:3000/failure',
    success_url: 'http://localhost:3000/success',
    country: 'ETH',
    currency: 'ETB'
  });

  const updateFormData = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const validateExpiryDate = (date) => {
    const today = new Date();
    const selectedDate = new Date(date);
    const maxDate = new Date(today.getTime() + (30 * 24 * 60 * 60 * 1000)); // 30 days from today
    
    if (selectedDate > maxDate) {
      Alert.alert('Invalid Date', 'Expiry date must be within 30 days from today');
      return false;
    }
    
    if (selectedDate < today) {
      Alert.alert('Invalid Date', 'Expiry date cannot be in the past');
      return false;
    }
    
    return true;
  };

  const handleCreatePaymentLink = async () => {
    // Validate expiry date before sending request
    if (!validateExpiryDate(formData.expiry_date)) {
      return;
    }

    setLoading(true);
    setResponse(null);
    
    try {
      const endpoint = activeTab === 'paymentLink' 
        ? 'http://localhost:3000/payments/link/create'
        : 'http://localhost:3000/payments/static-link/create';
      
      console.log('Calling endpoint:', endpoint);
      console.log('Payload:', formData);
      
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
      
      const data = await response.json();
      
      if (response.ok) {
        setResponse(data);
        Alert.alert('Success', `${activeTab === 'paymentLink' ? 'Payment Link' : 'Static Link'} created successfully!`);
      } else {
        Alert.alert('Error', data.message || 'Failed to create link');
        setResponse(data);
      }
    } catch (error) {
      console.error('Error:', error);
      Alert.alert('Error', 'Network error: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  const renderFormField = (label, field, placeholder, keyboardType = 'default', validation = null, readOnly = false) => (
    <View style={styles.formGroup}>
      <Text style={styles.label}>{label}</Text>
      <TextInput
        style={[styles.input, readOnly && styles.readOnlyInput]}
        value={formData[field]}
        onChangeText={(value) => {
          if (readOnly) return; // Don't allow changes for read-only fields
          if (validation && field === 'expiry_date') {
            if (validateExpiryDate(value)) {
              updateFormData(field, value);
            }
          } else {
            updateFormData(field, value);
          }
        }}
        placeholder={placeholder}
        keyboardType={keyboardType}
        editable={!readOnly}
      />
      {readOnly && (
        <Text style={styles.readOnlyNote}>Auto-generated by server</Text>
      )}
    </View>
  );

  const renderResponse = () => {
    if (!response) return null;

    return (
      <View style={styles.responseContainer}>
        <Text style={styles.responseTitle}>API Response:</Text>
        <ScrollView style={styles.responseContent}>
          <Text style={styles.responseText}>
            {JSON.stringify(response, null, 2)}
          </Text>
        </ScrollView>
      </View>
    );
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
        >
          <Ionicons name="arrow-back" size={24} color="#333" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>YagoutPay Link Testing</Text>
      </View>

      {/* Tab Selector */}
      <View style={styles.tabContainer}>
        <TouchableOpacity
          style={[styles.tab, activeTab === 'paymentLink' && styles.activeTab]}
          onPress={() => switchTab('paymentLink')}
        >
          <Text style={[styles.tabText, activeTab === 'paymentLink' && styles.activeTabText]}>
            Payment Link
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.tab, activeTab === 'staticLink' && styles.activeTab]}
          onPress={() => switchTab('staticLink')}
        >
          <Text style={[styles.tabText, activeTab === 'staticLink' && styles.activeTabText]}>
            Static Link
          </Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            {activeTab === 'paymentLink' ? 'Payment Link API Test' : 'Static Link API Test'}
          </Text>
          <Text style={styles.sectionDescription}>
            {activeTab === 'paymentLink' 
              ? 'Create a payment link using YagoutPay Payment Link API'
              : 'Create a static QR code link using YagoutPay Static Link API'
            }
          </Text>
          <Text style={styles.noteText}>
            ⚠️ Note: Expiry date must be within 30 days from today. Order IDs are auto-generated to prevent duplicates.
          </Text>
        </View>

        <View style={styles.form}>
          {renderFormField('Request User ID', 'req_user_id', 'Enter user ID')}
          {renderFormField('Merchant ID', 'me_id', 'Enter merchant ID')}
          {renderFormField('Amount', 'amount', 'Enter amount', 'numeric')}
          {renderFormField('Customer Email', 'customer_email', 'Enter email')}
          {renderFormField('Mobile Number', 'mobile_no', 'Enter mobile number', 'phone-pad')}
          {renderFormField('Expiry Date', 'expiry_date', 'YYYY-MM-DD', 'default', true)}
          {renderFormField('Order ID', 'order_id', 'Auto-generated', 'default', null, true)}
          {renderFormField('First Name', 'first_name', 'Enter first name')}
          {renderFormField('Last Name', 'last_name', 'Enter last name')}
          {renderFormField('Product', 'product', 'Enter product name')}
          {renderFormField('Dial Code', 'dial_code', 'Enter dial code')}
          {renderFormField('Failure URL', 'failure_url', 'Enter failure URL')}
          {renderFormField('Success URL', 'success_url', 'Enter success URL')}
          {renderFormField('Country', 'country', 'Enter country code')}
          {renderFormField('Currency', 'currency', 'Enter currency code')}
        </View>

        <TouchableOpacity
          style={[styles.submitButton, loading && styles.submitButtonDisabled]}
          onPress={handleCreatePaymentLink}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="white" />
          ) : (
            <Text style={styles.submitButtonText}>
              Create {activeTab === 'paymentLink' ? 'Payment Link' : 'Static Link'}
            </Text>
          )}
        </TouchableOpacity>

        {renderResponse()}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 15,
    backgroundColor: 'white',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  backButton: {
    marginRight: 15,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'white',
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 8,
    padding: 4,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 6,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: '#007AFF',
  },
  tabText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#666',
  },
  activeTabText: {
    color: 'white',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  section: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginTop: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  sectionDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  noteText: {
    fontSize: 12,
    color: '#FF6B6B',
    fontStyle: 'italic',
    marginTop: 8,
    textAlign: 'center',
  },
  form: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginTop: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  formGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#f9f9f9',
  },
  readOnlyInput: {
    backgroundColor: '#f0f0f0',
    borderColor: '#ccc',
    color: '#666',
  },
  readOnlyNote: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
    marginTop: 4,
  },
  submitButton: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  submitButtonDisabled: {
    backgroundColor: '#ccc',
  },
  submitButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  responseContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  responseTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  responseContent: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    maxHeight: 300,
  },
  responseText: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: '#333',
    lineHeight: 18,
  },
});

export default PaymentLinkTestScreen;

